DROP DATABASE IF EXISTS hospitalesBD;

CREATE DATABASE IF NO EXISTS hospitalesBD;

USE hospitalesBD;


CREATE TABLE HOSPITALES(

   HOSPITAL_COD INT(2)

     ,NOMBRE    VARCHAR(15)  

    ,DIRECCION VARCHAR(20)

, TELEFONO CHAR(8)

, NUM_CAMA INT(3)

, CONSTRAINT PK_HOSPITAL PRIMARY KEY (HOSPITAL_COD));


CREATE TABLE SALAS(

   SALA_COD INT(2)

, HOSPITAL_COD INT(2) NOT NULL

, NOMBRE VARCHAR(20)  

, NUM_CAMA INT(3)

, CONSTRAINT PK_SALA PRIMARY KEY (SALA_COD)

, CONSTRAINT FK_HOSPITAL_SALA FOREIGN KEY (HOSPITAL_COD)

REFERENCES HOSPITALES (HOSPITAL_COD))

    ON DELETE NO ACTION

    ON UPDATE CASCADE

;


CREATE TABLE PLANTILLAS(

  HOSPITAL_COD INT(2) NOT NULL

, SALA_COD INT(2) NOT NULL

, EMPLEADO_NO INT(4)

, APELLIDO VARCHAR(15)  

, FUNCION CHAR(10)

, TURNO CHAR (1)

, SALARIO INT(10)

, CONSTRAINT PK_EMPLEADO PRIMARY KEY (EMPLEADO_NO)

, CONSTRAINT FK_HOSPITAL FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD)

     ON DELETE NO ACTION

     ON UPDATE CASCADE

,

  CONSTRAINT FK_SALA FOREIGN KEY (SALA_COD) REFERENCES SALAS (SALA_COD)

   ON DELETE NO ACTION

   ON UPDATE CASCADE

,

  CONSTRAINT CH_TURNO CHECK (TURNO IN ('T', 'M', 'N')),

  CONSTRAINT CH_SALARIO CHECK (SALARIO > 0));


CREATE TABLE PACIENTES(

     INSCRIPCION INT(5)

     ,APELLIDO  VARCHAR(15)  

    ,DIRECCION VARCHAR(20)  

, NSS INT(9) NOT NULL

, CONSTRAINT PK_PACIENTE PRIMARY KEY (INSCRIPCION));


CREATE TABLE DIAGNOSTICOS(

     DIAG_COD INT(5)

     ,INSCRIPCION  INT(5)  

    ,DESCRIPCION VARCHAR(400)  

    ,RESPONSABLE  INT(4)  

, FECHA DATE

, NIVEL CHAR(6)

, CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (DIAG_COD)

, CONSTRAINT FK_PACIENTE FOREIGN KEY(INSCRIPCION) REFERENCES PACIENTES(INSCRIPCION)

 ON DELETE NO ACTION

 ON UPDATE CASCADE

, CONSTRAINT FK_PLANTILLAS FOREIGN KEY(RESPONSABLE) REFERENCES PLANTILLAS(EMPLEADO_NO)

 ON DELETE NO ACTION

 ON UPDATE CASCADE

, CONSTRAINT CK_NIVEL CHECK (NIVEL IN('ALTO','MEDIO','BAJO'))

);


CREATE TABLE OCUPACIONES(

 INSCRIPCION INT(5)

, HOSPITAL_COD INT(2)

, SALA_COD INT(2)

, CAMA INT(4)

, CONSTRAINT PK_OCUPACIONES PRIMARY KEY(INSCRIPCION,HOSPITAL_COD,SALA_COD)

, CONSTRAINT FK_PACIENTE_OCUP FOREIGN KEY (INSCRIPCION) REFERENCES PACIENTES(INSCRIPCION)

 ON DELETE NO ACTION

 ON UPDATE CASCADE

, CONSTRAINT FK_HOSPITAL_OCUP FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD)

 ON DELETE NO ACTION

 ON UPDATE CASCADE

, CONSTRAINT FK_SALA_OCUP FOREIGN KEY (SALA_COD) REFERENCES SALAS (SALA_COD)

 ON DELETE NO ACTION

 ON UPDATE CASCADE

);